[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "exputils"
readme = "README.md"
version = "0.0.0"
dependencies = [
    "numpy",
    "h5py",
    "tqdm"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
